[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "gunicorn app_production:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60 --preload"

[environments.production.variables]
RAILWAY_ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
